### ISSUE TITLE
IE9-10 stylesheet sometimes don't get parsed by -prefix-free

### ISSUE THREAD

**Issue by mgol** [LeaVerou/prefixfree#124]
See http://jsfiddle.net/xWKTP/
Works in Chrome, Firefox, breaks on IE9-10.

It also breaks on localhost when the CSS file is replaced by a LESS one. See comments below for further details.

**Comment by mgol** [comment]
I see "transform" is correctly added to PrefixFree.properties but it's not correctly handled afterwards.

**Comment by mgol** [comment]
Actually, it does work if you try it in a simple HTML with a separate stylesheet, outside of jsFiddle. I'm using -prefix-free together with LESS in my project and that's where it breaks. I was able to create a minimal example that shows the bug outside jsFiddle. HTML is:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Test page</title>
    <link rel="stylesheet/less" href="style.less">
    <script src="less.js"></script>
    <script src="prefixfree.js"></script>
</head>
<body>
    <div></div>
</body>
</html>
```

where prefixfree.js and less.js are latest official versions and `style.css` is as follows:

``` css
div {
    position: absolute;
    top: 0;
    left: 0;
    width: 200px;
    height: 100px;
    background-color: red;
    transform: rotate(90deg);
}
```

**Comment by mgol** [comment]
OK, after further analysis it appears to be a problem in LESS. With the simples `style.css` ever:

``` css
body {
    background-color: black;
}
```

and this HTML:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Test page</title>
    <link rel="stylesheet/less" href="style.less">
    <script src="less.js"></script>
    <script>
        console.log(document.querySelectorAll('style')[0].outerHTML);
    </script>
</head>
<body>
</body>
</html>
```

in Chrome & Firefox I get this:

``` css
<style type="text/css" id="less:style">body {
  background-color: black;
}
</style>
```

whereas in IE9 this:

```
LOG: <style id="less:style" type="text/css"></style> 
```

IE10 behaves in the same way.

Seems like some kind of a race condition... I'll report it to LESS devs (oh, boy, why there always has to be sth different in IE...).
