### ISSUE TITLE
Add support for @supports

### ISSUE THREAD

**Issue by joelspadin** [LeaVerou/prefixfree#137]
PrefixFree doesn't seem to work on the conditions of an @supports block. For example, ideally, this...

``` css
@supports (object-fit: contain) {
    img { object-fit: contain; }
}
```

...would translate to this in Opera...

``` css
@supports (-o-object-fit: contain) {
    img { -o-object-fit: contain; }
}
```
