### ISSUE TITLE
 box-sizing not getting prefixed in FireFox v27

### ISSUE THREAD

**Issue by aand16** [LeaVerou/prefixfree#186]
Hi!
I don't know if it's a bug of FF, because, strangely, in your example page box-sizing gets prefixed.
Instead, in my page it doesn't get replaced:

``` css
* {
    box-sizing: border-box;
}
```

gets me

``` css
* {
}
```
