### ISSUE TITLE
Support for LESS

### ISSUE THREAD

**Issue by Anahkiasen** [LeaVerou/prefixfree#52]
Hi,
I was wondering, is there any way to make Prefixfree compatible with Less.js ? Make it add prefixes to .less files compiled on-the-fly ?

**Comment by DavidBradbury** [comment]
I personally haven't tested this yet, but I imagine Less.js should work just fine with the Dynamic DOM plugin. If I have time later I'll test it out and see the results.

**Comment by DavidBradbury** [comment]
Seems to work just fine:

**index.htm**

``` HTML
<!DOCTYPE HTML>
<html lang=en>
<meta charset=UTF-8>
<title>-prefix-free + LESS.js</title>

<link rel="stylesheet/less" type="text/css" href="style.less">

<script src="prefixfree.min.js"></script>
<script src="prefixfree.dynamic-dom.min.js"></script>
<script src="less-1.3.0.min.js" type="text/javascript"></script>

<h1>-prefix-free + LESS.js</h1>
<p>Testing <a href="#">transitions using less and -prefix-free.</a>
```

``` CSS
@my-blue: #36a;

body {
    font-family: Arial, sans-serif;
    text-align: center;
}

h1 {
    font-size: 32px;
    font-weight: bold;
}

p {
    font-size: 16px;
    transition: all 1s;
    padding: 4px 0;
    a {
        padding: 3px;
        font-weight: bold;
        color: @my-blue;
        text-decoration: none;
        text-shadow: 0 0 0 #fff;
        transition: all 1s;

        &:hover { 
            color: #fff;
            text-shadow: 0 0 5px @my-blue;
        }
    }
    &:hover {
        background: #333;
        color: #fff;
    }
}
```
