### ISSUE TITLE
Line break after transition causes non-prefixed values

### ISSUE THREAD

**Issue by maxhoffmann** [LeaVerou/prefixfree#96]
Adding a line break after `transition` causes non-prefixed values.

Example:

``` css
.not-working {
 transition:
   transform linear 1s;  // transform will not be prefixed, transition will
}

.works {
 transition: transform linear 1s;  // both will be prefixed
}
```

I think `transition` is the only case, where a prefixed property can have prefixed values. Can’t come up with another one at the moment.

**Comment by maxhoffmann** [comment]
Totally nonsense but this one works with line breaks.

``` css
.before {
 transition:
   linear-gradient();
}

.after {
 -prefix-transition:
   -prefix-linear-gradient();
}
```
